export const PRODUCT_CATEGORIES = [
  'T-Shirts','Mugs','Button Pins','Eco Bags','Mousepads',
  'Ref Magnets','Stickers','Ballpens','Caps','Souvenirs','Other',
];

export const initCollections = [
  { id: 'col1', title: 'T-Shirts',      slug: 't-shirts',    isPublished: true  },
  { id: 'col2', title: 'Drinkware',     slug: 'drinkware',   isPublished: true  },
  { id: 'col3', title: 'Accessories',   slug: 'accessories', isPublished: true  },
  { id: 'col4', title: 'Office & Desk', slug: 'office-desk', isPublished: true  },
  { id: 'col5', title: 'Bags & Totes',  slug: 'bags-totes',  isPublished: true  },
  { id: 'col6', title: 'New Arrivals',  slug: 'new-arrivals',isPublished: false },
];

export const initProducts = [
  {
    id: 'pr1',
    name: 'Custom White T-Shirt',
    description: 'Personalized white t-shirt with DTF or sublimation printing. Available in all sizes.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b1',
    pricingMode: 'tiered',
    tiers: [
      { id: 't1a', minQty: 1,  maxQty: 10,   prices: { __base__: 350 } },
      { id: 't1b', minQty: 11, maxQty: 25,   prices: { __base__: 320 } },
      { id: 't1c', minQty: 26, maxQty: null, prices: { __base__: 290 } },
    ],
    collectionIds: ['col1'],
    isCustomizable: true, allowCOD: true, isMadeToOrder: false,
    downpaymentPct: 50, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-01',
  },
  {
    id: 'pr2',
    name: 'Custom Black T-Shirt',
    description: 'Personalized black t-shirt with DTF printing.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b2',
    pricingMode: 'fixed', price: 380,
    collectionIds: ['col1'],
    isCustomizable: true, allowCOD: true, isMadeToOrder: false,
    downpaymentPct: 50, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-01',
  },
  {
    id: 'pr3',
    name: 'Ceramic Mug 11oz',
    description: 'Sublimation-printed ceramic white mug 11oz. Perfect for custom photo or design prints.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b8',
    pricingMode: 'tiered',
    tiers: [
      { id: 't3a', minQty: 1,  maxQty: 5,    prices: { __base__: 260 } },
      { id: 't3b', minQty: 6,  maxQty: 12,   prices: { __base__: 240 } },
      { id: 't3c', minQty: 13, maxQty: null, prices: { __base__: 220 } },
    ],
    collectionIds: ['col2'],
    isCustomizable: true, allowCOD: false, isMadeToOrder: false,
    downpaymentPct: 50, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-02',
  },
  {
    id: 'pr8',
    name: 'Inner Color Mug 11oz',
    description: 'Sublimation-printed inner color mug 11oz. Available in Black and Red inner. Great for vibrant prints.',
    images: [], thumbnail: '',
    type: 'multi-variant',
    pricingMode: 'tiered',
    variants: [
      { id: 'vm1', name: 'Black Inner', bomId: 'b9' },
      { id: 'vm2', name: 'Red Inner',   bomId: 'b10' },
    ],
    tiers: [
      { id: 't8a', minQty: 1,  maxQty: 5,    prices: { vm1: 280, vm2: 280 } },
      { id: 't8b', minQty: 6,  maxQty: 12,   prices: { vm1: 260, vm2: 260 } },
      { id: 't8c', minQty: 13, maxQty: null, prices: { vm1: 240, vm2: 240 } },
    ],
    collectionIds: ['col2'],
    isCustomizable: true, allowCOD: false, isMadeToOrder: false,
    downpaymentPct: 50, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-02',
  },
  {
    id: 'pr9',
    name: 'Magic Mug 11oz',
    description: 'Heat-activated magic mug 11oz. Design reveals when hot liquid is poured in.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b11',
    pricingMode: 'tiered',
    tiers: [
      { id: 't9a', minQty: 1,  maxQty: 5,    prices: { __base__: 320 } },
      { id: 't9b', minQty: 6,  maxQty: 12,   prices: { __base__: 300 } },
      { id: 't9c', minQty: 13, maxQty: null, prices: { __base__: 280 } },
    ],
    collectionIds: ['col2'],
    isCustomizable: true, allowCOD: false, isMadeToOrder: false,
    downpaymentPct: 50, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-02',
  },
  {
    id: 'pr4',
    name: 'Custom Button Pin 2.25"',
    description: 'Personalized button pin with your custom design.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b4',
    pricingMode: 'tiered',
    tiers: [
      { id: 't4a', minQty: 1,  maxQty: 24,   prices: { __base__: 65 } },
      { id: 't4b', minQty: 25, maxQty: 49,   prices: { __base__: 55 } },
      { id: 't4c', minQty: 50, maxQty: null, prices: { __base__: 45 } },
    ],
    collectionIds: ['col3'],
    isCustomizable: true, allowCOD: true, isMadeToOrder: false,
    downpaymentPct: 0, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-03',
  },
  {
    id: 'pr5',
    name: 'Custom Eco Bag',
    description: 'Canvas eco bag with sublimation or DTF printed design.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b5',
    pricingMode: 'inquiry',
    collectionIds: ['col5'],
    isCustomizable: true, allowCOD: false, isMadeToOrder: true,
    downpaymentPct: 50, hideWhenOutOfStock: false, isPublished: false, createdAt: '2025-04-05',
  },
  {
    id: 'pr6',
    name: 'Custom Mousepad',
    description: 'Full-color sublimation printed mousepad 22×18cm.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b6',
    pricingMode: 'fixed', price: 350,
    collectionIds: ['col4'],
    isCustomizable: true, allowCOD: true, isMadeToOrder: false,
    downpaymentPct: 50, hideWhenOutOfStock: true, isPublished: true, createdAt: '2025-04-06',
  },
  {
    id: 'pr7',
    name: 'Custom Ref Magnet',
    description: 'Personalized refrigerator magnet with your custom design.',
    images: [], thumbnail: '',
    type: 'standalone', bomId: 'b7',
    pricingMode: 'tiered',
    tiers: [
      { id: 't7a', minQty: 1,  maxQty: 9,   prices: { __base__: 120 } },
      { id: 't7b', minQty: 10, maxQty: 24,  prices: { __base__: 100 } },
      { id: 't7c', minQty: 25, maxQty: null, prices: { __base__: 85 } },
    ],
    collectionIds: ['col3'],
    isCustomizable: true, allowCOD: true, isMadeToOrder: false,
    downpaymentPct: 0, hideWhenOutOfStock: false, isPublished: true, createdAt: '2025-04-07',
  },
];
